name: Build `tar.gz` PyPI
on:
  push:
    tags:
      - "v*"
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools>=67.2.0"
          pip install wheel build
      - name: Build
        run: |
          python -m build --sdist
          cd dist
          pip install *.tar.gz
      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.MY_PYPI_API_TOKEN_2023_06_22 }}
      - name: Archive Wheels in dist/*.whl
        uses: actions/upload-artifact@v3
        with:
          name: dist-wheels-all
          path: |
            dist
            !dist/**/*.md
